CREATE TABLE "todos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "todos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text DEFAULT (auth.user_id()) NOT NULL,
	"task" text NOT NULL,
	"is_complete" boolean DEFAULT false NOT NULL,
	"inserted_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "todos" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "crud-app_user-policy-select" ON "todos" AS PERMISSIVE FOR SELECT TO "app_user" USING ((select auth.user_id() = "todos"."user_id"));--> statement-breakpoint
CREATE POLICY "crud-app_user-policy-insert" ON "todos" AS PERMISSIVE FOR INSERT TO "app_user" WITH CHECK ((select auth.user_id() = "todos"."user_id"));--> statement-breakpoint
CREATE POLICY "crud-app_user-policy-update" ON "todos" AS PERMISSIVE FOR UPDATE TO "app_user" USING ((select auth.user_id() = "todos"."user_id")) WITH CHECK ((select auth.user_id() = "todos"."user_id"));--> statement-breakpoint
CREATE POLICY "crud-app_user-policy-delete" ON "todos" AS PERMISSIVE FOR DELETE TO "app_user" USING ((select auth.user_id() = "todos"."user_id"));